### ISSUE TITLE
Where do I specify accordion content using <px-accordion> <px-accordion header-value="ytutyru" show-action="true" status="ttttt 4rewrewr" icons='{"more":"px-utl:chevron-right","less":"px-utl:chevron","action":"px-utl:edit"}' >           Accordion content goes here.         </px-accordion> "Accordion content goes here." is not visible on toggle 

### ISSUE THREAD

**Issue by abhishek-servicemax** [PredixDev/px-accordion#1]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
Once you've created your code example, you can save it under a new url.
Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by mdwragg** [comment]
Please fill out issue following the info requested in the template. Thanks.

**Comment by abhishek-servicemax** [comment]
Expected behavior:
on click of header of accordion Shows or hides the accordion content
actual behavior:
on click of header of accordion content or child of accordion is not visible 

Steps to reproduce the problem:

<px-accordion header-value="Header Caption" status="Last Updated: 3 Days Ago" header-value="Header Caption" >
<span>this text should visible on click of header but it's not visible</span>
</px-accordion>

Environment (component version number, Browser (including version), operating system, hardware, etc):
I am using Predix Component inside React Component
Browser(google chrome)
operating system(macOs)

Screenshots:
![accordian-content](https://user-images.githubusercontent.com/23258624/30844839-71c6c96e-a2ae-11e7-9099-88b59dc248b0.png)
