### ISSUE TITLE
ease of dynamically adding content

### ISSUE THREAD

**Issue by weAllWeGot** [PredixDev/px-accordion#3]
# Submit an Issue

Hi,

This component works great for the most part thanks!
This is less of an issue and more of a suggestion/question.

## Expected behavior and actual behavior:

If i have a `px-accordion` component like this:
```HTML
<px-accordion
   id="mm-freq-tag-accordion"
   header-value="Most Frequently Occurring Tags">       
</px-accordion>
```

And I want to use javascript to dynamically populate it with content I would try this:

```javascript
document.getElementById("mm-freq-tag-accordion").innerHTML = "<p>ex 1</p><p>ex 2</p><p>ex 3</p>";
```
This is what you get with the above code:
![image](https://user-images.githubusercontent.com/13176059/31514395-8147206a-af5f-11e7-98bd-dc6ee7ee0bd3.png)

Instead I had to do this:

```javascript
document.getElementById("mm-freq-tag-accordion").getElementsByClassName("accordion__body")[0].innerHTML = "<p>ex 1</p><p>ex 2</p><p>ex 3</p>";
```
This works and yields the following behavior:

![success_accordion](https://user-images.githubusercontent.com/13176059/31514567-00ebf610-af60-11e7-8615-d58e1154f878.gif)

## Steps to reproduce the problem:
Shown above

## Suggestion/Question
I'm not sure if this should either be included in the documentation or if there should be some type of method to add content easily? Alternatively I may be missing some other way to do this more simply.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

component version: 1.07
browser: Google Chrome: Version 61.0.3163.100 (Official Build) (64-bit)
OS: Windows 7, Professional x64

## Screenshots (_optional, but very helpful_):
Included above
## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
Once you've created your code example, you can save it under a new url.
Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

https://codepen.io/anon/pen/oGMQWV?editors=1011

**Comment by randyaskin** [comment]
I think you'll want to use the "Polymer way" of doing this, as your workaround violates shadow DOM encapsulation so it may stop working at some point, or may not work in all browsers. Try this:

```
var acc = document.getElementById("mm-freq-tag-accordion");
Polymer.dom(acc).innerHTML = "<p>ex 1</p><p>ex 2</p><p>ex 3</p>";
```
Note: `Polymer.dom()` will be going away when we migrate to Polymer 2 - I'm not sure if your initial attempt will be the new "right way" or if there is a different syntax.
