### ISSUE TITLE
Polymer 2.x compatibility; "header-value" not working

### ISSUE THREAD

**Issue by squidbe** [PredixDev/px-accordion#4]
Need Polymer 2.x "slot" api.
Also, "header-value" attribute not working with vs. 2.x

## Steps to reproduce the problem:
Use Polymer 2.1.1.
Wrap content in px-accordion and use the "header-value" attribute.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
px-accordion 1.0.7
Chrome 61
Mac El Capitan

## Screenshots (_optional, but very helpful_):
![screen shot 2017-10-16 at 11 54 53 am](https://user-images.githubusercontent.com/1664227/31629721-52095f68-b269-11e7-8906-ce9f871f3d30.png)

## Code examples
        <px-accordion
            icons='{"more":"px-utl:chevron-right","less":"px-utl:chevron","action":"px-utl:edit"}'
            header-value="Header Testing"
            status="">
            <div class="table-container">
                <div class="data-table" ref="tblContainer"></div>
            </div>
        </px-accordion>
(Table content is dynamically added -- it shows when I add the &lt;slot&gt; tag.

**Comment by davidrleonard** [comment]
The https://github.com/PredixDev/px-accordion/tree/polymer2.0-preview branch addresses this issue. To use this branch right now while it's still in preview, install px-accordion in your bower.json from that branch (you'll also want to get the polymer2.0-preview branch for px-icon-set):

```
...
"dependencies" : {
  "px-accordion" : "polymer2.0-preview",
  "px-icon-set" : "polymer2.0-preview",
},
"resolutions" : {
  "webcomponentsjs": "^1.0.0",
  "px-icon-set" : "polymer2.0-preview"
}
...
```

**Comment by JuanCarlosC** [comment]
After making the changes mentioned above, the "header-value" attribute is still not appearing. The screen shot and code example is the same from the comment above as I am on the same console project with @squidbe.

**Comment by davidrleonard** [comment]
@juancarlosc @squidbe There is another commit on the polymer2.0-preview branch that should address this. Can you confirm it fixes the issue for you after you run bower install and get the newest version?

**Comment by squidbe** [comment]
@davidrleonard Works now, thx!
