### ISSUE TITLE
Accordion open state

### ISSUE THREAD

**Issue by eyalezer** [PredixDev/px-accordion#6]
on open state the accordion body should't be with **overflow: hidden**

in case of usage of elements that can go over the container width or height (like tooltips etc) then the open state of the accordion body should be with **overflow: visible** to display the elements properly

**Comment by mdwragg** [comment]
Hi, thanks for your issue. Though, can you please fill the issue in according to the template provided when you hit 'New Issue'. The explanation above doesn't sufficiently explain the issue you're facing or why we should make the change.

Thanks.
