### ISSUE TITLE
issue on generating accordion with dynamic values i am using in angular applications 

### ISSUE THREAD

**Issue by nraafee** [PredixDev/px-accordion#7]
Hello Team,

i am trying to use PX_Accordion. the syntax i am using to generate dynamic accordion header but it is throwing  error. and it is not generating with the dynamic value.

Regards,
Raafee N

**Comment by randyaskin** [comment]
What error is it throwing?

**Comment by nraafee** [comment]
Sorry its working its a small mistake i did in the polymer extension file
